<?php

namespace App\Support\Migrations;

use App\Enums\AttributeDataType;
use App\Enums\AttributeStatus;
use App\Enums\AttributeStorageType;

/**
 * Canonical Customer system field seed data for GAP-016 Field Foundation migration.
 */
final class FieldFoundationCustomerSeed
{
    public const CODES = [
        'name',
        'short_name',
        'edrpou',
        'ipn',
        'onec_guid',
        'email',
        'manager_name',
        'manager_phone',
        'account_manager_id',
        'backup_manager_id',
        'is_active',
        'payment_delay_days',
        'credit_limit',
        'current_debt',
        'default_price_list_id',
    ];

    /**
     * @return array<string, array<string, mixed>>
     */
    public static function definitions(): array
    {
        return [
            'name' => [
                'data_type' => AttributeDataType::Text,
                'is_localizable' => false,
                'is_multi_value' => false,
                'localized_labels' => ['uk' => 'Назва'],
                'description' => null,
                'validation_rules' => null,
                'status' => AttributeStatus::Active,
            ],
            'short_name' => [
                'data_type' => AttributeDataType::Text,
                'is_localizable' => false,
                'is_multi_value' => false,
                'localized_labels' => ['uk' => 'Скорочена назва'],
                'description' => null,
                'validation_rules' => null,
                'status' => AttributeStatus::Active,
            ],
            'edrpou' => [
                'data_type' => AttributeDataType::Text,
                'is_localizable' => false,
                'is_multi_value' => false,
                'localized_labels' => ['uk' => 'ЄДРПОУ'],
                'description' => null,
                'validation_rules' => null,
                'status' => AttributeStatus::Active,
            ],
            'ipn' => [
                'data_type' => AttributeDataType::Text,
                'is_localizable' => false,
                'is_multi_value' => false,
                'localized_labels' => ['uk' => 'ІПН'],
                'description' => null,
                'validation_rules' => null,
                'status' => AttributeStatus::Active,
            ],
            'onec_guid' => [
                'data_type' => AttributeDataType::Text,
                'is_localizable' => false,
                'is_multi_value' => false,
                'localized_labels' => ['uk' => 'Ідентифікатор 1С'],
                'description' => null,
                'validation_rules' => null,
                'status' => AttributeStatus::Active,
            ],
            'email' => [
                'data_type' => AttributeDataType::Text,
                'is_localizable' => false,
                'is_multi_value' => false,
                'localized_labels' => ['uk' => 'Email'],
                'description' => null,
                'validation_rules' => null,
                'status' => AttributeStatus::Active,
            ],
            'manager_name' => [
                'data_type' => AttributeDataType::Text,
                'is_localizable' => false,
                'is_multi_value' => false,
                'localized_labels' => ['uk' => 'Контактна особа'],
                'description' => null,
                'validation_rules' => null,
                'status' => AttributeStatus::Active,
            ],
            'manager_phone' => [
                'data_type' => AttributeDataType::Text,
                'is_localizable' => false,
                'is_multi_value' => false,
                'localized_labels' => ['uk' => 'Телефон контактної особи'],
                'description' => null,
                'validation_rules' => null,
                'status' => AttributeStatus::Active,
            ],
            'account_manager_id' => [
                'data_type' => AttributeDataType::Select,
                'is_localizable' => false,
                'is_multi_value' => false,
                'localized_labels' => ['uk' => 'Відповідальний менеджер'],
                'description' => null,
                'validation_rules' => null,
                'status' => AttributeStatus::Active,
            ],
            'backup_manager_id' => [
                'data_type' => AttributeDataType::Select,
                'is_localizable' => false,
                'is_multi_value' => false,
                'localized_labels' => ['uk' => 'Резервний менеджер'],
                'description' => null,
                'validation_rules' => null,
                'status' => AttributeStatus::Active,
            ],
            'is_active' => [
                'data_type' => AttributeDataType::Boolean,
                'is_localizable' => false,
                'is_multi_value' => false,
                'localized_labels' => ['uk' => 'Активний'],
                'description' => null,
                'validation_rules' => null,
                'status' => AttributeStatus::Active,
            ],
            'payment_delay_days' => [
                'data_type' => AttributeDataType::Number,
                'is_localizable' => false,
                'is_multi_value' => false,
                'localized_labels' => ['uk' => 'Відстрочка платежу, днів'],
                'description' => null,
                'validation_rules' => null,
                'status' => AttributeStatus::Active,
            ],
            'credit_limit' => [
                'data_type' => AttributeDataType::Money,
                'is_localizable' => false,
                'is_multi_value' => false,
                'localized_labels' => ['uk' => 'Кредитний ліміт'],
                'description' => null,
                'validation_rules' => null,
                'status' => AttributeStatus::Active,
            ],
            'current_debt' => [
                'data_type' => AttributeDataType::Money,
                'is_localizable' => false,
                'is_multi_value' => false,
                'localized_labels' => ['uk' => 'Поточна заборгованість'],
                'description' => null,
                'validation_rules' => null,
                'status' => AttributeStatus::Active,
            ],
            'default_price_list_id' => [
                'data_type' => AttributeDataType::Select,
                'is_localizable' => false,
                'is_multi_value' => false,
                'localized_labels' => ['uk' => 'Прайс-лист за замовчуванням'],
                'description' => null,
                'validation_rules' => null,
                'status' => AttributeStatus::Active,
            ],
        ];
    }

    /**
     * @return array<string, array<string, mixed>>
     */
    public static function bindings(): array
    {
        $visibility = static fn (bool $admin, bool $b2b): array => [
            'admin' => $admin,
            'b2b' => $b2b,
            'channels' => [],
        ];

        return [
            'name' => [
                'storage_type' => AttributeStorageType::Column,
                'storage_path' => 'customers.name',
                'field_group' => 'basic_information',
                'sort_order' => 10,
                'is_required' => true,
                'is_filterable' => true,
                'is_sortable' => true,
                'visibility_settings' => $visibility(true, true),
                'status' => AttributeStatus::Active,
            ],
            'is_active' => [
                'storage_type' => AttributeStorageType::Column,
                'storage_path' => 'customers.is_active',
                'field_group' => 'basic_information',
                'sort_order' => 20,
                'is_required' => true,
                'is_filterable' => true,
                'is_sortable' => true,
                'visibility_settings' => $visibility(true, false),
                'status' => AttributeStatus::Active,
            ],
            'short_name' => [
                'storage_type' => AttributeStorageType::Column,
                'storage_path' => 'customers.short_name',
                'field_group' => 'basic_information',
                'sort_order' => 30,
                'is_required' => false,
                'is_filterable' => true,
                'is_sortable' => true,
                'visibility_settings' => $visibility(true, false),
                'status' => AttributeStatus::Active,
            ],
            'edrpou' => [
                'storage_type' => AttributeStorageType::Column,
                'storage_path' => 'customers.edrpou',
                'field_group' => 'identifiers',
                'sort_order' => 10,
                'is_required' => false,
                'is_filterable' => true,
                'is_sortable' => false,
                'visibility_settings' => $visibility(true, false),
                'status' => AttributeStatus::Active,
            ],
            'ipn' => [
                'storage_type' => AttributeStorageType::Column,
                'storage_path' => 'customers.ipn',
                'field_group' => 'identifiers',
                'sort_order' => 20,
                'is_required' => false,
                'is_filterable' => true,
                'is_sortable' => false,
                'visibility_settings' => $visibility(true, false),
                'status' => AttributeStatus::Active,
            ],
            'onec_guid' => [
                'storage_type' => AttributeStorageType::Column,
                'storage_path' => 'customers.onec_guid',
                'field_group' => 'identifiers',
                'sort_order' => 30,
                'is_required' => false,
                'is_filterable' => true,
                'is_sortable' => false,
                'visibility_settings' => $visibility(true, false),
                'status' => AttributeStatus::Active,
            ],
            'email' => [
                'storage_type' => AttributeStorageType::Column,
                'storage_path' => 'customers.email',
                'field_group' => 'contacts',
                'sort_order' => 10,
                'is_required' => false,
                'is_filterable' => true,
                'is_sortable' => false,
                'visibility_settings' => $visibility(true, false),
                'status' => AttributeStatus::Active,
            ],
            'manager_name' => [
                'storage_type' => AttributeStorageType::Column,
                'storage_path' => 'customers.manager_name',
                'field_group' => 'contacts',
                'sort_order' => 20,
                'is_required' => false,
                'is_filterable' => false,
                'is_sortable' => false,
                'visibility_settings' => $visibility(true, false),
                'status' => AttributeStatus::Active,
            ],
            'manager_phone' => [
                'storage_type' => AttributeStorageType::Column,
                'storage_path' => 'customers.manager_phone',
                'field_group' => 'contacts',
                'sort_order' => 30,
                'is_required' => false,
                'is_filterable' => false,
                'is_sortable' => false,
                'visibility_settings' => $visibility(true, false),
                'status' => AttributeStatus::Active,
            ],
            'default_price_list_id' => [
                'storage_type' => AttributeStorageType::Relation,
                'storage_path' => 'Customer.defaultPriceList',
                'field_group' => 'commercial_terms',
                'sort_order' => 10,
                'is_required' => false,
                'is_filterable' => true,
                'is_sortable' => false,
                'visibility_settings' => $visibility(true, false),
                'status' => AttributeStatus::Active,
            ],
            'payment_delay_days' => [
                'storage_type' => AttributeStorageType::Column,
                'storage_path' => 'customers.payment_delay_days',
                'field_group' => 'commercial_terms',
                'sort_order' => 20,
                'is_required' => false,
                'is_filterable' => false,
                'is_sortable' => true,
                'visibility_settings' => $visibility(true, false),
                'status' => AttributeStatus::Active,
            ],
            'credit_limit' => [
                'storage_type' => AttributeStorageType::Column,
                'storage_path' => 'customers.credit_limit',
                'field_group' => 'commercial_terms',
                'sort_order' => 30,
                'is_required' => false,
                'is_filterable' => false,
                'is_sortable' => true,
                'visibility_settings' => $visibility(true, false),
                'status' => AttributeStatus::Active,
            ],
            'current_debt' => [
                'storage_type' => AttributeStorageType::Column,
                'storage_path' => 'customers.current_debt',
                'field_group' => 'commercial_terms',
                'sort_order' => 40,
                'is_required' => false,
                'is_filterable' => false,
                'is_sortable' => true,
                'visibility_settings' => $visibility(true, false),
                'status' => AttributeStatus::Active,
            ],
            'account_manager_id' => [
                'storage_type' => AttributeStorageType::Relation,
                'storage_path' => 'Customer.accountManager',
                'field_group' => 'internal',
                'sort_order' => 10,
                'is_required' => false,
                'is_filterable' => true,
                'is_sortable' => false,
                'visibility_settings' => $visibility(true, false),
                'status' => AttributeStatus::Active,
            ],
            'backup_manager_id' => [
                'storage_type' => AttributeStorageType::Relation,
                'storage_path' => 'Customer.backupManager',
                'field_group' => 'internal',
                'sort_order' => 20,
                'is_required' => false,
                'is_filterable' => false,
                'is_sortable' => false,
                'visibility_settings' => $visibility(true, false),
                'status' => AttributeStatus::Active,
            ],
        ];
    }
}
